### ISSUE TITLE
Config to change crate's drop rates and item drops

### ISSUE THREAD

**Issue by Lucipo** [Draylar/go-fish#19]
There isn't a lot of config and some things are not compatible with other mods and some could benefit from other mods.

We could begin with crates by a kind-of in-depth config on each crate and what they can drop, the chances of each item, and what can come out of the crates.

**Comment by Draylar** [comment]
Go Fish is already fully configurable through data-packs. You can see all the loot tables used by Go Fish [here](https://github.com/Draylar/go-fish/tree/master/src/main/resources/data/gofish/loot_tables/gameplay/fishing). Go Fish also overrides the standard fishing loot table [here](https://github.com/Draylar/go-fish/tree/master/src/main/resources/data/minecraft/loot_tables/gameplay). As an example, the Diamond Crate table is found [here](https://github.com/Draylar/go-fish/blob/master/src/main/resources/data/gofish/loot_tables/gameplay/fishing/diamond_crate.json). If you want to modify these or provide compatibility between multiple fishing mods, you can ship a data-pack that overrides one or more of these loot tables with your modpack/server.

*note: Go Fish also injects into the standard/overworld fishing loot table [here](https://github.com/Draylar/go-fish/blob/master/src/main/java/draylar/gofish/registry/GoFishLootHandler.java), because loot tables do not have an append option/functionality, and I would rather not nuke fish from other mods. I could add a config option for these in the future, but there really isn't anything you would need to config here, outside completely removing a fish from the drop tables.
