### ISSUE TITLE
Config to change where fish are fished

### ISSUE THREAD

**Issue by Lucipo** [Draylar/go-fish#20]
Simple, some mods add new biomes and you cant catch the new fish in those biomes.

**Comment by Draylar** [comment]
Almost every Fish/Crate drop in Go Fish is dependent on Biome Category rather than direct biomes, so biome mods will/should be compatible. The only outlier are things like the Gilded Blackstone crate, [which only drop in the Basalt Detlas](https://github.com/Draylar/go-fish/blob/043e8683aa2399308e087be13f330636fea9a372/src/main/resources/data/gofish/loot_tables/gameplay/fishing/crates.json#L102). 

What fish are you trying to catch, and what biome are you trying to catch them in?

**Comment by Lucipo** [comment]
Our issue was no one could ever find a new fish but that was resolved already. Thanks for responding though. We are using https://www.curseforge.com/minecraft/mc-mods/vanilla-biomes and I dont know if we just happened to fish in a vanilla biome and it worked or if its just coincidence.

**Comment by Draylar** [comment]
Good to hear it was resolved, feel free to re-open this issue or create a new one if you encounter it again. Thanks for the report!
