### ISSUE TITLE
Deepfry enchant doesn't work?

### ISSUE THREAD

**Issue by varencilator** [Draylar/go-fish#26]
Fish still come raw from what I can tell

**Comment by ArtiTice** [comment]
I second this. Fishing with enchantment on fishing rod doesn't seem to cook fish when they're caught. Unless that's not what the enchantment does?

**Comment by Draylar** [comment]
Could you send me your mod list? Might be a conflict. I have a modded rod with Deepfry, and it seems to properly cook the fish that are caught.

![image](https://user-images.githubusercontent.com/17728338/119399697-d0de0d00-bc9e-11eb-8be2-7abfbd6d1976.png)

**Comment by ArtiTice** [comment]
I just tested the deep fry enchantment in-game and it seems to cook fish only when its using a new modded fishing rod. It doesn't work on vanilla fishing rods. Is this intentional? I haven't been able to find any information anywhere about the deep fry enchantment. 

Here's my mod list as well. There are a lot of mods, let me know if you'd like me to help test them all to single out a conflicting mod.
[modlist.txt](https://github.com/Draylar/go-fish/files/6535996/modlist.txt)

**Comment by Draylar** [comment]
Oops, you're right! I'm pushing a quick fix in 1.2.3, so Deepfry should now work on the vanilla rod. Let me know if you encounter any other problems.
